### PR TITLE
fix: falsy IDs breaking relationships

### LINKED ISSUE #729: Relationship with falsy ID (i.e. 0) not serialized
*   **Platform**: macOS 10.13
*   **Database**: postgres 9
*   **Lux Version**: 1.2.2
*   **Node Version**: 9

There are two problems causing relationships with `0` as it's ID not to be handled correctly. 

1. https://github.com/postlight/lux/blob/7bf2478bd0305d65549f9b9fe98997f51dc07ae0/src/packages/database/query/runner/utils/build-results.js#L112  here relationships fall through when the value is 0 (because it's falsy of course) and thus aren't put into the Model instance properly.

2.  https://github.com/postlight/lux/blob/7bf2478bd0305d65549f9b9fe98997f51dc07ae0/src/packages/serializer/index.js#L629 here the relationships are only formatted when the relationship ID isn't falsy.

For both I suspect checking if the value is either `null` or `undefined` is enough.

### PR DESCRIPTION
**Pull request by nickschot**
fixes #729

### CODE REVIEW

**Comment by nickschot** [comment]
I'd like to add a test for this but for some reason tests aren't running. Will look further into it tomorrow. For CI it seems to be due to node version (?)

**Comment by nickschot** [comment]
They seem to have resolved themselves.

**Comment by jamemackson** [comment]
@zacharygolba is there anything further you are looking for before merging this PR?

**Comment by zacharygolba** [comment]
Nice work @nickschot! Sorry for the delay.

**Pull request merged**
