### PR TITLE
fix: compiler does not properly format class names for nested namespaces

### LINKED ISSUE #446: Error when trying to namespace api/v1
I'm getting an unexpected token error when trying to have a namespace `api/v1`
```
ApiV1::UserController
    ^^^
```

This happens after I run `lux g resource api/v1/user`

### PR DESCRIPTION
**Pull request by zacharygolba**
Closes #446

### CODE REVIEW

**Comment by seawatts** [comment]
Looks good. 👍  Can't wait to get all the tests in so we can verify this functionality in a unit test =)

**Comment by seawatts** [comment]
Actually, this doesn't seem to fix the problem. I'm still getting

```
Building your application...{ SyntaxError: ./dist/index.js: Unexpected token (12:19)
  10 |
  11 | export {
> 12 |   default as Api$V1::ApplicationController
     |                    ^
  13 | } from '../app/controllers/api/v1/application.js';
  14 |
  15 | export {
```

**Comment by zacharygolba** [comment]
How did you test that?

**Comment by seawatts** [comment]
`npm i -g postlight/lux#cb4c9eb`
`cd ~/.nvm/versions/node/v6.6.0/lib/node_modules/lux-framework`
`npm i`
`npm run build`
`cd /tmp`
`lux new test-server`
`lux g resource api/v1/user`
- Edit the `app/routes.js` file
```js
// app/routes.js
export default function routes() {
  this.namespace('api', function() {
    this.namespace('v1', function() {
      this.resource('users');
    });
  });
}
```
`lux s`

First I got the error
```
 ReferenceError: Could not resolve controller by name 'api/application'
    at ControllerMissingError (/private/tmp/test-server/dist/bundle.js:7519:5)
    at Object.namespace (/private/tmp/test-server/node_modules/lux-framework/src/packages/router/definitions/context/index.js:58:21)
```
Then I added `app/controllers/api/application.js`
Then I get the error
```
 ReferenceError: Could not resolve controller by name 'api/v1/application'
    at ControllerMissingError (/private/tmp/test-server/dist/bundle.js:7519:5)
    at Object.namespace (/private/tmp/test-server/node_modules/lux-framework/src/packages/router/definitions/context/index.js:58:21)
```

**Comment by zacharygolba** [comment]
@seawatts this should be good now 👍

**Comment by zacharygolba** [comment]
Also closes #450

**Pull request merged**
