### PR TITLE
Feat: Setting default configuration

### LINKED ISSUE #257: Use a Default Config Object Internally
Currently Lux relies on a user defined config file to be 100% accurate in order to run and build the application. We should have a default internal config file that the user defined config is deep merged with using the [merge util](https://github.com/postlight/lux/blob/master/src/utils/merge.js).

--

We probably want to do this within the [loader package](https://github.com/postlight/lux/blob/master/src/packages/loader/index.js) so that way it covers all uses of the config object throughout the application.

### PR DESCRIPTION
**Pull request by adampash**
This PR adds a default configuration object based on the CLI generator templates. @zacharygolba — I'm sure you might want to make some adjustments, but... here's a starting point!

--

Closes #257

### CODE REVIEW

**Comment by zacharygolba** [comment]
This is a great start! As per the changes suggested in our meeting I'm adding the `needs-update` label for the time being. 😃

**Comment by adampash** [comment]
@zacharygolba hopefully this is closer to what you were thinking!

**Comment by zacharygolba** [comment]
👏  Awesome job! I have one small request.

Can we dry up the `Application$opts` type in [`./src/packages/application/interfaces.js`](https://github.com/postlight/lux/blob/a69ba164a488e011846a79baa0b4c8925b7d0119/src/packages/application/interfaces.js)?

```javascript
// @flow
import type { Config } from '../config';
import type { Database$config } from '../database';

export type Application$opts = Config & {
  path: string;
  port: number;
  database: Database$config;
};
```

**Comment by adampash** [comment]
Ah yes forgot about that! Updating now.

**Comment by zacharygolba** [comment]
Just found a small bug. As usual it's 100% my fault! 😆 

If you only export an empty object from the test app config you run into the following error.

```
TypeError: Cannot read property 'level' of undefined
    at new Logger (/Users/zacharygolba/workspace/postlight/lux/src/packages/logger/index.js:164:66)
    at /Users/zacharygolba/workspace/postlight/lux/src/packages/cli/commands/serve.js:26:18
    at next (native)
    at step (/Users/zacharygolba/workspace/postlight/lux/src/utils/set-type.js:22:3)
    at /Users/zacharygolba/workspace/postlight/lux/src/utils/set-type.js:22:3
    at /Users/zacharygolba/workspace/postlight/lux/src/utils/set-type.js:22:3
    at serve (/Users/zacharygolba/workspace/postlight/lux/src/packages/cli/commands/serve.js:16:1)
    at exec (/Users/zacharygolba/workspace/postlight/lux/bin/lux:63:18)
    at exec.then (/Users/zacharygolba/workspace/postlight/lux/bin/lux:151:19)
```

You were right all along! We should merge the config file in the `loader` as well as the `Application`'s `constructor`. This will prevent instances of `Logger` running outside of `Application` instances from throwing errors.

**Comment by zacharygolba** [comment]
Just finished testing this. It works great! Awesome job 😃

**Pull request merged**
