### PR TITLE
Feat: Added generator for utils

### PR DESCRIPTION
**Pull request by adampash**
Addresses #255

### CODE REVIEW

**Comment by zacharygolba** [comment]
👍  works great!

One thing though (my fault). I forgot to put the ability to run `lux d util` and `lux d middleware` in the issue descriptions for #254 and #255. Can you add that to this PR before merging?

**Comment by adampash** [comment]
All right added the delete for utilities, too. I'm afraid that because I'd started updating the middleware branch in preparation for merging, it unfortunately ended up cascading commits... but it's hopefully not a big problem.

**Comment by zacharygolba** [comment]
That should be fine. Reviewing now...

**Comment by zacharygolba** [comment]
👍  Works great!

**Pull request merged**
